### PR TITLE
support hawkthorne characters

### PR DESCRIPTION
**Pull request by NimbusBP1729**
@calhoun137 this PR is designed to support proper display of the character sprite sheets by pressing the "Enable Character Mode" button

I noticed there's a weird bug in master where a single digit representing frames cycles through all frames before setting on the one that was entered(#3)

[EDIT: I now realize you may have considered that bug a feature]

All of the character state positions are read from the JSON object we use in-game

reasons why I wouldn't merge this:
1) works only on firefox and chrome
2) changed the default sprite to a character one just for testing purposes
3) the code may be too hawkthorne specific if you were intending to make something general

I can work out kinks in IE soon.

### CODE REVIEW

**Comment by NimbusBP1729** [comment]
worked out kinks in ie

**Comment by calhoun137** [comment]
ok awesome!  I will take a look at this weekend and merge it (im at work
right now)

Cheers!

**Comment by calhoun137** [comment]
I feel like these changes are too specific to merge them into the master branch, because like you, said my goal was to make something that is very general.  However I am really happy that you and many others have found this app so useful and I do appreciate that choosing the frame numbers can be a little annoying, especially for larger sprite sheets.  I really like your approach of using an external json file for predefined animations that can be chosen from a drop down.  In the spirit of keeping things general i think another good approach would be to allow specific frames to be highlighted with a mouse click, possibly displaying the results with an overlaying canvas element.  As you can see I don't have a lot of projects on github, and it made me really happy to see my first ever pull request :)

**Comment by NimbusBP1729** [comment]
that's a good idea! and because I like JSON I bet we could make a standard where we could have the selected options saved as a JSON object so we can reuse it later.

**Comment by calhoun137** [comment]
Definitely. Even better, we can cache the results in localStorage.

**Pull request closed without merging**
